In [1]:
import torch
from torch import nn
import bert
import tensorflow as tf
from typing import Optional
from einops import rearrange, repeat

2024-02-01 11:59:23.454102: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-01 11:59:24.054279: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-01 11:59:25.622222: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
# Credit to microsoft phi-2 code (put something like this in final piece of code)

In [3]:
# testing Embedding dimensions and calculations (done)
class Embedding(nn.Module):
    """Token embedding with dropout."""
    def __init__(self, vocab_size, n_embd) -> None:
        super().__init__()
        self.wte = nn.Embedding(vocab_size, n_embd)

    def forward(self, input_ids: torch.LongTensor) -> torch.FloatTensor:
        input_shape = input_ids.size()
        input_ids = input_ids.view(-1, input_shape[-1])
        hidden_states = self.wte(input_ids)
        return hidden_states

# testing py
py_layer = Embedding(vocab_size=3000, n_embd=768)
input = torch.randint(0, 3000, (4,))
# print(py_layer(input))
# testing tf
matrix = py_layer.wte._parameters['weight'].data.numpy()
matrix = tf.convert_to_tensor(matrix)
tf_layer = bert.Embedding(4, 768, matrix)
# print(tf_layer(input))

2024-02-01 11:59:28.622281: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-01 11:59:28.622675: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [4]:
# testing _apply_rotary_emb() (done)
def MY_apply_rotary_emb(x, cos, sin): # code mostly taken from original
    print("x.shape:", x.shape)
    assert(len(x.shape) == 4)
    assert(len(cos.shape) == 2)
    _, seqlen, _, _ = x.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    x_rot = x[:, :, :, :rotary_dim]
    # print("x_rot", x_rot.shape)
    x_pass = x[:, :, :, rotary_dim:]
    x1, x2 = tf.split(x_rot, 2, axis=-1) # assumption that tf.split behaves the same as nn.chunk
    c = tf.expand_dims(cos[:seqlen], axis=1)
    s = tf.expand_dims(sin[:seqlen], axis=1)
    x1, x2, c, s = [tf.cast(t, tf.float32) for t in [x1, x2, c, s]]
    for i in [x1, x2, c, s]: print(i.shape)
    x_rot = tf.concat([x1 * c - x2 * s, x1 * s + x2 * c], axis=-1)
    x_rot = tf.cast(x_rot, x.dtype) # might fail due to passing in x.dtype
    return tf.concat([x_rot, x_pass], axis=-1)


def _apply_rotary_emb(
    x: torch.FloatTensor,
    cos: torch.FloatTensor,
    sin: torch.FloatTensor,
) -> torch.FloatTensor:
    print("x.shape:", x.shape)
    _, seqlen, _, _ = x.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    x_rot = x[:, :, :, :rotary_dim]
    # print("x_rot", x_rot.shape)
    x_pass = x[:, :, :, rotary_dim:]
    x1, x2 = x_rot.chunk(2, dim=-1)
    c, s = rearrange(cos[:seqlen], "s d -> s 1 d"), rearrange(sin[:seqlen], "s d -> s 1 d")
    x1, x2, c, s = [t.to(dtype=torch.float32) for t in [x1, x2, c, s]]
    for i in [x1, x2, c, s]: print(i.shape)
    x_rot = torch.cat([x1 * c - x2 * s, x1 * s + x2 * c], axis=-1).to(x.dtype)
    return torch.cat([x_rot, x_pass], axis=-1)

last_dim = 5 # it seems this is neccesary
x = torch.randn([2,3,2,last_dim*2]) 
cos = torch.randn([4,last_dim])
sin = torch.randn([4,last_dim])
# print(_apply_rotary_emb(x, cos, sin))
# print("-----")
x = tf.constant(x.numpy())
cos = tf.constant(cos.numpy())
sin = tf.constant(sin.numpy())
# print(MY_apply_rotary_emb(x, cos, sin))

In [5]:
# testing _apply_rotary_emb_kv (done)
def MY_apply_rotary_emb_kv(kv, cos, sin, cos_k=None, sin_k=None):
    assert(len(kv.shape) == 5)
    assert(len(cos.shape) == 2)
    if cos_k is not None: assert(len(cos_k.shape) == 4)
    if cos_k is not None: assert(cos_k.shape == sin_k.shape)
    _, seqlen, _, _, _ = kv.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    k_rot = kv[:, :, 0, :, :rotary_dim]
    k_pass = kv[:, :, 0, :, rotary_dim:]
    k1, k2 = tf.split(k_rot, 2, axis=-1)
    c = tf.expand_dims(cos[:seqlen], axis=1)
    s = tf.expand_dims(sin[:seqlen], axis=1)
    k1, k2, c, s = [tf.cast(t, tf.float32) for t in [k1, k2, c, s]]
    k_rot = tf.concat([k1 * c - k2 * s, k1 * s + k2 * c], axis=-1)
    k_rot = tf.cast(k_rot, kv.dtype)
    return tf.concat([
        tf.expand_dims(tf.concat([k_rot, k_pass], axis=-1), axis=2),
        kv[:, :, 1:2, :, :],
    ], axis=2)

def _apply_rotary_emb_kv(
    kv: torch.FloatTensor,
    cos: torch.FloatTensor,
    sin: torch.FloatTensor,
    cos_k= None,
    sin_k= None,
) -> torch.FloatTensor:
    _, seqlen, _, _, _ = kv.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    k_rot = kv[:, :, 0, :, :rotary_dim]
    k_pass = kv[:, :, 0, :, rotary_dim:]
    k1, k2 = k_rot.chunk(2, dim=-1)
    c, s = rearrange(cos[:seqlen], "s d -> s 1 d"), rearrange(sin[:seqlen], "s d -> s 1 d")
    k1, k2, c, s = [t.to(dtype=torch.float32) for t in [k1, k2, c, s]]
    k_rot = torch.cat([k1 * c - k2 * s, k1 * s + k2 * c], axis=-1).to(kv.dtype)
    return torch.cat(
        [
            torch.cat([k_rot, k_pass], axis=-1).unsqueeze(2),
            kv[:, :, 1:2, :, :],
        ],
        axis=2,
    )

last_dim = 5 
kv = torch.randn([2,3,2, 8, last_dim*2]) 
cos = torch.randn([4,last_dim])
sin = torch.randn([4,last_dim])
cos_k = torch.randn([4, 5, 6, last_dim])
sin_k = torch.randn([4, 5, 6, last_dim])
# print(_apply_rotary_emb_kv(kv, cos, sin, cos_k, sin_k))
# print("-----")
kv = tf.constant(kv.numpy())
cos = tf.constant(cos.numpy())
sin = tf.constant(sin.numpy())
cos_k = tf.constant(cos_k.numpy())
sin_k = tf.constant(sin_k.numpy())

# print(MY_apply_rotary_emb_kv(kv, cos, sin, cos_k, sin_k))

In [6]:
# testing _apply_rotary_emb_qkv (done)

def MY_apply_rotary_emb_qkv(qkv, cos, sin, cos_k=None, sin_k=None):
    assert(len(qkv.shape) == 5)
    assert(len(cos.shape) == 2)
    if cos_k is not None: assert(len(cos_k.shape) == 4)
    if cos_k is not None: assert(cos_k.shape == sin_k.shape)
    _, seqlen, _, _, _ = qkv.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    q_rot = qkv[:, :, 0, :, :rotary_dim]
    q_pass = qkv[:, :, 0, :, rotary_dim:]
    k_rot = qkv[:, :, 1, :, :rotary_dim]
    k_pass = qkv[:, :, 1, :, rotary_dim:]
    q1, q2 = tf.split(q_rot, 2, axis=-1)
    k1, k2 = tf.split(k_rot, 2, axis=-1)
    c = tf.expand_dims(cos[:seqlen], axis=1)
    s = tf.expand_dims(sin[:seqlen], axis=1)
    q1, q2, k1, k2, c, s = [tf.cast(t, tf.float32) for t in [q1, q2, k1, k2, c, s]]
    q_rot = tf.concat([q1 * c - q2 * s, q1 * s + q2 * c], axis=-1)
    q_rot = tf.cast(q_rot, qkv.dtype)
    k_rot = tf.concat([k1 * c - k2 * s, k1 * s + k2 * c], axis=-1)
    k_rot = tf.cast(k_rot, qkv.dtype)
    return tf.concat([
        tf.expand_dims(tf.concat([q_rot, q_pass], axis=-1), axis=2),
        tf.expand_dims(tf.concat([k_rot, k_pass], axis=-1), axis=2),
        qkv[:, :, 2:3, :, :],
    ], axis=2)

def _apply_rotary_emb_qkv(
    qkv: torch.FloatTensor,
    cos: torch.FloatTensor,
    sin: torch.FloatTensor,
    cos_k=None,
    sin_k=None,
) -> torch.FloatTensor:
    _, seqlen, _, _, _ = qkv.shape
    _, rotary_dim = cos.shape
    rotary_dim *= 2
    q_rot = qkv[:, :, 0, :, :rotary_dim]
    q_pass = qkv[:, :, 0, :, rotary_dim:]
    k_rot = qkv[:, :, 1, :, :rotary_dim]
    k_pass = qkv[:, :, 1, :, rotary_dim:]
    q1, q2 = q_rot.chunk(2, dim=-1)
    k1, k2 = k_rot.chunk(2, dim=-1)
    c, s = rearrange(cos[:seqlen], "s d -> s 1 d"), rearrange(sin[:seqlen], "s d -> s 1 d")
    q1, q2, k1, k2, c, s = [t.to(dtype=torch.float32) for t in [q1, q2, k1, k2, c, s]]
    q_rot = torch.cat([q1 * c - q2 * s, q1 * s + q2 * c], axis=-1).to(qkv.dtype)
    k_rot = torch.cat([k1 * c - k2 * s, k1 * s + k2 * c], axis=-1).to(qkv.dtype)
    return torch.cat(
        [   torch.cat([q_rot, q_pass], axis=-1).unsqueeze(2),
            torch.cat([k_rot, k_pass], axis=-1).unsqueeze(2),
            qkv[:, :, 2:3, :, :],
        ],
        axis=2,
    )

last_dim = 5 
qkv = torch.randn([2,3,2, 8, last_dim*2])
cos = torch.randn([4,last_dim])
sin = torch.randn([4,last_dim])
cos_k = torch.randn([4, 5, 6, last_dim])
sin_k = torch.randn([4, 5, 6, last_dim])
# print(_apply_rotary_emb_kv(qkv, cos, sin, cos_k, sin_k))
# print("-----")
qkv = tf.constant(qkv.numpy())
cos = tf.constant(cos.numpy())
sin = tf.constant(sin.numpy())
cos_k = tf.constant(cos_k.numpy())
sin_k = tf.constant(sin_k.numpy())
# print(MY_apply_rotary_emb_kv(qkv, cos, sin, cos_k, sin_k))

In [44]:
# testing rotary embedding layer (done)
class MyRotaryEmbedding(tf.Module):
    def __init__(
        self, 
        dim: int,
        base: int = 10000,
        scale_base: float = None,
        pos_idx_in_fp32: bool = True,
        max_position_embeddings: int = 2048,
        name=None,
        **kwargs
        ):
        super().__init__(name)
        if scale_base is not None:
            raise NotImplementedError
        self.dim = dim
        self.base = float(base)
        self.scale_base = scale_base
        self.pos_idx_in_fp32 = pos_idx_in_fp32
        self.max_position_embeddings = max_position_embeddings
        # Generate and save the inverse frequency buffer (non-trainable)
        self.inv_freq = self._compute_inv_freq()
        # Generate and save the scale buffer (non-trainable)
        self.scale = (
            (tf.range(0, dim, 2, dtype=tf.float32) + 0.4 * dim) / (1.4 * dim)
            if scale_base is not None
            else None)
        self._update_cos_sin_cache(max_position_embeddings, dtype=tf.float32)

    def _compute_inv_freq(self):
        return 1.0 / (self.base ** (tf.range(0, self.dim, 2, dtype=tf.float32) / self.dim))

    def _update_cos_sin_cache(self, seqlen:int, dtype):
        self._seq_len_cached = seqlen
        # fp32 is preferred since the output of `torch.arange` can be quite large
        # and bf16 would lose a lot of precision
        if self.pos_idx_in_fp32:
            t = tf.range(seqlen, dtype=tf.float32)
            if self.inv_freq.dtype != tf.float32:
                inv_freq = self._compute_inv_freq()
            else:
                inv_freq = self.inv_freq
        else:
            t = tf.range(seqlen, dtype=self.inv_freq.dtype)
            inv_freq = self.inv_freq
        # `torch.outer` is preferred since `torch.einsum` converts from fp32 to fp16 if used with AMP
        # tensorflow does not appear to do what the top comment states
        freqs = tf.einsum('i,j->ij', t, inv_freq)
        if self.scale is None:
            self._cos_cached = tf.cast(tf.cos(freqs), dtype=dtype)
            self._sin_cached = tf.cast(tf.sin(freqs), dtype=dtype)
        else:
            power = (tf.range(seqlen, dtype=self.scale.dtype) - seqlen // 2) / self.scale_base
            scale = self.scale ** tf.expand_dims(power, axis=1)
            # Force the scale multiplciation to happen in fp32
            self._cos_cached = tf.cast((tf.cos(freqs) * scale), dtype=dtype)
            self._sin_cached = tf.cast((tf.sin(freqs) * scale), dtype=dtype)
            self._cos_k_cached = tf.cast((tf.cos(freqs) / scale), dtype=dtype)
            self._sin_k_cached = tf.cast((tf.sin(freqs) / scale), dtype=dtype)
    
    def __call__(self, qkv, kv, seqlen_offset, **kwargs):
        if (
            self._seq_len_cached < qkv.shape[1] + seqlen_offset
            or self._cos_cached.device != qkv.device
            or self._cos_cached.dtype != qkv.dtype
            # or (self.training and self._cos_cached.is_inference()) # look into this
        ):
            self._update_cos_sin_cache(qkv.shape[1] + seqlen_offset, dtype=qkv.dtype)
            print("case 1")
        else:
            print("case 2")
        if kv is None:
            return MY_apply_rotary_emb_qkv(
                qkv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],)
        else:
            # print("qkv:", qkv.shape)
            # print("_cos_cached:", self._cos_cached[seqlen_offset:].shape)
            # print("_sin_cached:", self._sin_cached[seqlen_offset:].shape)
            q = MY_apply_rotary_emb(
                qkv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],)
            kv = MY_apply_rotary_emb_kv(
                kv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],)
            return q, kv
    ################################
class RotaryEmbedding(nn.Module):
    def __init__(
        self,
        dim: int,
        base: int = 10000,
        scale_base= None,
        pos_idx_in_fp32: bool = True,
        max_position_embeddings: int = 2048,
        device = None,
        **kwargs,
    ) -> None:
        super().__init__()
        if scale_base is not None:
            raise NotImplementedError
        self.dim = dim
        self.base = float(base)
        self.scale_base = scale_base
        self.pos_idx_in_fp32 = pos_idx_in_fp32
        self.max_position_embeddings = max_position_embeddings
        self.device = device
        # Generate and save the inverse frequency buffer (non-trainable)
        inv_freq = self._compute_inv_freq(device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)

        # Generate and save the scale buffer (non-trainable)
        scale = (
            (torch.arange(0, dim, 2, device=device, dtype=torch.float32) + 0.4 * dim) / (1.4 * dim)
            if scale_base is not None
            else None
        )
        self.register_buffer("scale", scale, persistent=False)

        # Initialize cached attributes since ONNX can't rely on dynamic initialization
        self._update_cos_sin_cache(max_position_embeddings, device=device, dtype=torch.float32)

    def _compute_inv_freq(self, device: Optional[str] = None) -> torch.FloatTensor:
        return 1.0 / (self.base ** (torch.arange(0, self.dim, 2, device=device, dtype=torch.float32) / self.dim))

    def _update_cos_sin_cache(
        self,
        seqlen: int,
        device: Optional[str] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> None:
        self._seq_len_cached = seqlen

        # fp32 is preferred since the output of `torch.arange` can be quite large
        # and bf16 would lose a lot of precision
        if self.pos_idx_in_fp32:
            t = torch.arange(seqlen, device=device, dtype=torch.float32)
            if self.inv_freq.dtype != torch.float32:
                inv_freq = self._compute_inv_freq(device=device)
            else:
                inv_freq = self.inv_freq
        else:
            t = torch.arange(seqlen, device=device, dtype=self.inv_freq.dtype)
            inv_freq = self.inv_freq

        # `torch.outer` is preferred since `torch.einsum` converts from fp32 to fp16 if used with AMP
        freqs = torch.outer(t, inv_freq)
        if self.scale is None:
            self._cos_cached = torch.cos(freqs).to(dtype)
            self._sin_cached = torch.sin(freqs).to(dtype)
        else:
            power = (
                torch.arange(seqlen, dtype=self.scale.dtype, device=self.scale.device) - seqlen // 2
            ) / self.scale_base
            scale = self.scale.to(device=power.device) ** rearrange(power, "s -> s 1")

            # Force the scale multiplication to happen in fp32
            self._cos_cached = (torch.cos(freqs) * scale).to(dtype)
            self._sin_cached = (torch.sin(freqs) * scale).to(dtype)
            self._cos_k_cached = (torch.cos(freqs) / scale).to(dtype)
            self._sin_k_cached = (torch.sin(freqs) / scale).to(dtype)

    def forward(
        self,
        qkv: torch.Tensor,
        kv: Optional[torch.Tensor] = None,
        seqlen_offset: int = 0,
        **kwargs,
    ):
        if (
            self._seq_len_cached < qkv.shape[1] + seqlen_offset
            or self._cos_cached.device != qkv.device
            or self._cos_cached.dtype != qkv.dtype
            or (self.training and self._cos_cached.is_inference())
        ):
            self._update_cos_sin_cache(qkv.shape[1] + seqlen_offset, device=qkv.device, dtype=qkv.dtype)
            print("case 1")
        else:
            print("case 2")
        if kv is None:
            return _apply_rotary_emb_qkv(
                qkv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],
            )
        else:
            # print("qkv:", qkv.shape)
            # print("_cos_cached:", self._cos_cached[seqlen_offset:].shape)
            # print("_sin_cached:", self._sin_cached[seqlen_offset:].shape)
            q = _apply_rotary_emb(
                qkv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],
            )
            kv = _apply_rotary_emb_kv(
                kv,
                self._cos_cached[seqlen_offset:],
                self._sin_cached[seqlen_offset:],
            )

            return q, kv


dim = 5
base = 5000
scale_base = None
pos_idx_in_fp32 = False
max_position_embeddings = 2048
device = 'cpu'

rot_emb = RotaryEmbedding(dim, base, scale_base, pos_idx_in_fp32, max_position_embeddings, device)
tf_rot_emb = MyRotaryEmbedding(dim, base, scale_base, pos_idx_in_fp32, max_position_embeddings)

# test with kv being something, and being None

# it appears that if kv will be none, then qkv must be 4d rather than 5d

last_dim = 5
# qkv = torch.randn([2,3,2, 8, last_dim*2]) 
qkv = torch.randn([2,3, 8, last_dim*2]) # making qkv
kv = torch.randn([2,3,2, 8, last_dim*2])
seqlen_offset = 4
print(rot_emb(qkv, kv, seqlen_offset))
print("-----")
qkv = tf.constant(qkv.numpy())
kv = tf.constant(kv.numpy())
print(tf_rot_emb(qkv, kv, seqlen_offset))

case 2
x.shape: torch.Size([2, 3, 8, 10])
torch.Size([2, 3, 8, 3])
torch.Size([2, 3, 8, 3])
torch.Size([3, 1, 3])
torch.Size([3, 1, 3])
(tensor([[[[-1.8938e+00, -4.1029e-01, -8.8421e-01, -1.9304e-01, -1.2140e-01,
           -1.0539e+00, -1.4824e-02, -1.5790e-02,  6.0957e-01, -1.3694e+00],
          [ 8.0937e-01,  1.1165e+00, -1.2808e-01,  1.9952e+00,  5.9032e-01,
           -9.3814e-01, -5.7851e-02,  1.3259e+00,  1.0572e-01, -6.2015e-01],
          [ 6.2096e-01,  5.4155e-01, -2.1747e-01, -4.6848e-01, -4.1188e-02,
            9.9107e-01, -1.8650e+00,  3.3280e-01, -1.6502e+00, -2.0197e+00],
          [ 2.3909e-01,  6.3765e-01, -7.6045e-02,  5.6865e-01, -2.5666e+00,
            1.5488e-01,  3.1994e-01, -3.4196e-01, -1.0873e-01, -6.4962e-01],
          [-4.8921e-01, -2.8636e-01,  3.6575e-01,  1.3399e+00,  2.5697e+00,
            3.5761e-01, -3.1746e-01,  1.0271e+00, -5.4583e-01, -7.2060e-01],
          [ 1.1611e+00,  7.6173e-01, -6.9356e-01,  2.6104e-02, -1.0691e+00,
            1.6318e+00

In [8]:
# testing Linear Layer
layer = torch.nn.Linear(3, 5)
input = torch.randn([7,3])
print(layer(input))
weights = tf.cast(torch.detach(layer.weight).numpy(), dtype=tf.float32)
bias = tf.cast(torch.detach(layer.bias).numpy(), dtype=tf.float32)
linear = bert.Dense_v2(3, 5, weights, bias=bias)
input = tf.cast(input.numpy(), dtype=tf.float32)
print(linear(input))

tensor([[-0.3245, -0.0591,  0.6093, -0.1040, -0.7552],
        [ 0.7832,  0.7040, -0.8370,  0.0035,  0.8881],
        [ 0.0339,  0.8532,  0.2983,  0.0426, -0.2447],
        [ 0.5386,  0.1699, -0.0566,  0.0462, -0.1206],
        [ 0.0076,  0.7232, -0.5018, -0.1676,  0.6907],
        [ 0.3041, -0.0959,  0.1605, -0.0091, -0.3878],
        [-0.2141,  0.4867,  0.1948, -0.1034, -0.1485]],
       grad_fn=<AddmmBackward0>)
tf.Tensor(
[[ 0.90998816  0.764223   -0.65371203 -0.20212054 -0.3200668 ]
 [-0.4556808  -0.11932212  0.36024922 -0.0818251   0.5056948 ]
 [ 0.49138063  0.12101516  0.58125836 -0.04253865  0.03689446]
 [ 0.23134461  0.7114701  -0.49200276 -0.4596124  -0.14770705]
 [-0.06815962 -0.44666833  0.5968875   0.35498527  0.62488246]
 [ 0.46989405  0.9027568  -0.8334268  -0.4704327  -0.28691515]
 [ 0.5129371   0.11793047  0.17815518  0.09346697  0.11931678]], shape=(7, 5), dtype=float32)


In [9]:
import math
class NewGELU(tf.Module):
    def __init__(self, name=None):
        super().__init__(name)
    def __call__(self, input):
        return 0.5 * input * (1.0 + tf.tanh(math.sqrt(2.0 / math.pi) * (input + 0.044715 * tf.pow(input, 3.0))))

In [10]:
# MLP (need to fill in the weight, bias, and activation) (works)

class MyMLP(tf.Module):
    def __init__(self, n_inner:int, n_embd:int, name=None): # manually written in act-fn()
        super().__init__(name)
        self.fc1 = bert.Dense_v2(n_embd, n_inner, weights=None, bias=None)
        self.fc2 = bert.Dense_v2(n_inner, n_embd, weights=None, bias=None)
        self.act = NewGELU
    def __call__(self, hidden_states):
        hidden_states = self.fc1(hidden_states)
        hidden_states = self.act(hidden_states)
        hidden_states = self.fc2(hidden_states)
        return hidden_states

class NewGELUActivation(nn.Module): # grabbed from hugging face
    def forward(self, input):
        return 0.5 * input * (1.0 + torch.tanh(math.sqrt(2.0 / math.pi) * (input + 0.044715 * torch.pow(input, 3.0))))
    

# input = torch.randn([2,3])
# print(input)
# layer = NewGELUActivation()
# print(layer(input))
# input = tf.constant(input.numpy())
# layer = NewGELU()
# print(layer(input))

In [11]:
# Looks good

# not sure what key_padding_mask dims are supposed to be in reality

def mask_fill(matrix, mask, value):
    inv_mask = (-1 * mask) + 1
    return inv_mask * matrix + (value * mask)

class MySelfAttention(tf.Module):
    def __init__(self, softmax_scale:float, name=None):
        super().__init__(name)
        self.softmax_scale = softmax_scale
    def __call__(self, qkv, key_padding_mask=None):
        batch_size, seqlen = qkv.shape[0], qkv.shape[1]
        q, k, v = tf.unstack(qkv, axis=2)
        q = tf.cast(q, dtype=tf.float32)
        k = tf.cast(k, dtype=tf.float32)
        softmax_scale = self.softmax_scale
        # Autocast is manually disabled to avoid `torch.einsum` performing the operation
        scores = tf.einsum("bthd,bshd->bhts", q, k * softmax_scale)
        # print(scores)
        if key_padding_mask is not None:
            padding_mask = tf.fill((batch_size, seqlen), -10000.0)
            padding_mask = tf.cast(padding_mask, dtype=scores.dtype)
            # print(padding_mask)
            padding_mask = mask_fill(padding_mask, key_padding_mask, 3.0)
            # print(padding_mask)
            scores = scores + tf.expand_dims(tf.expand_dims(padding_mask, axis=1), axis=1)
        # print(scores)
        # i am assuming this to be causal
        causal_mask = tf.experimental.numpy.triu(tf.fill((seqlen, seqlen), -10000.0), 1) # might need to be replaced
        scores = scores + tf.cast(causal_mask, dtype=scores.dtype)
        # print(scores)
        attention = tf.cast(tf.nn.softmax(scores, axis=-1), dtype=v.dtype)
        # print(attention)
        output = tf.einsum("bhts,bshd->bthd", attention, v)
        return output

class SelfAttention(nn.Module):
    def __init__(
        self,
        causal: bool = True,
        softmax_scale: Optional[float] = None,
        attention_dropout: float = 0.0,
    ) -> None:
        super().__init__()
        self.causal = causal
        self.softmax_scale = softmax_scale
        self.drop = nn.Dropout(attention_dropout)
    @torch.autocast("cpu", enabled=False)
    def forward(
        self,
        qkv: torch.FloatTensor,
        causal: bool = None,
        key_padding_mask: Optional[torch.BoolTensor] = None,
        **kwargs,
    ) -> torch.FloatTensor:
        batch_size, seqlen = qkv.shape[0], qkv.shape[1]
        q, k, v = qkv.unbind(dim=2)
        q = q.to(torch.float32)
        k = k.to(torch.float32)
        causal = self.causal if causal is None else causal
        softmax_scale = self.softmax_scale or 1.0 / math.sqrt(q.shape[-1])
        # Autocast is manually disabled to avoid `torch.einsum` performing the operation
        # using float16, which might lead to overflow
        scores = torch.einsum("bthd,bshd->bhts", q, k * softmax_scale)
        # print(scores)
        if key_padding_mask is not None:
            padding_mask = torch.full((batch_size, seqlen), -10000.0, dtype=scores.dtype, device=scores.device)
            # print(padding_mask)
            padding_mask.masked_fill_(key_padding_mask, 3.0)
            # print(padding_mask)
            scores = scores + rearrange(padding_mask, "b s -> b 1 1 s")
        # print(scores)
        if causal:
            causal_mask = torch.triu(torch.full((seqlen, seqlen), -10000.0, device=scores.device), 1)
            scores = scores + causal_mask.to(dtype=scores.dtype)
        # print(scores)
        attention = torch.softmax(scores, dim=-1).to(v.dtype)
        # print(attention)
        attention = self.drop(attention)
        output = torch.einsum("bhts,bshd->bthd", attention, v)
        return output

my_self_atten = MySelfAttention(softmax_scale=0.1)
self_atten = SelfAttention(softmax_scale=0.1)

batch_size = 1
seq_len = 17
last_dim = 5
# qkv = torch.randn([2,3,2, 8, last_dim*2])
# qkv = torch.randn([2,3, 8, last_dim*2]) # making qkv
qkv = torch.randn([batch_size, seq_len, 3, 5, 11])
key_padding_mask = torch.zeros((batch_size, seq_len), dtype=torch.float32)
key_padding_mask[0,0] += 1
key_padding_mask[0,1] += 1
key_padding_mask = key_padding_mask.to(bool)
out = self_atten(qkv, causal=True, key_padding_mask=key_padding_mask)
# print(out)
print("-----")
qkv = tf.constant(qkv.numpy())
key_padding_mask = tf.constant(key_padding_mask.to(torch.float).numpy())
out = my_self_atten(qkv, key_padding_mask=key_padding_mask)
# print(out)

-----


In [12]:
# looks good

class MyCrossAttention(tf.Module):
    def __init__(self, softmax_scale, name=None): # assume to be causal
        super().__init__(name)
        self.softmax_scale = softmax_scale
    def __call__(self, q, kv, key_padding_mask):
        batch_size, seqlen_q = q.shape[0], q.shape[1]
        seqlen_k = kv.shape[1]
        if kv.shape[3] != kv.shape[2]:
            kv = tf.repeat(kv, repeats=q.shape[2] // kv.shape[3], axis=-2)
        k, v = tf.unstack(kv, axis=2)
        q = tf.cast(q, dtype=tf.float32)
        k = tf.cast(k, dtype=tf.float32)
        print("q", q.shape)
        print("kv", kv.shape)
        print("k", k.shape)
        scores = tf.einsum("bthd,bshd->bhts", q, k * self.softmax_scale)
        if key_padding_mask is not None:
            padding_mask = tf.fill((batch_size, seqlen_k), -10000.0)
            padding_mask = tf.cast(padding_mask, dtype=scores.dtype)
            print("padding_mask:", padding_mask.shape)
            print("key_padding_mask:", key_padding_mask.shape)
            padding_mask = mask_fill(padding_mask, key_padding_mask, 0.0)
            scores = scores + tf.expand_dims(tf.expand_dims(padding_mask, axis=1), axis=1)
        # causal stuff
        rows = tf.expand_dims(tf.range(seqlen_q, dtype=tf.int64), axis=1) # if this fails, do axis=-1
        cols = tf.range(seqlen_k, dtype=tf.int64)
        causal_mask = cols > rows + seqlen_k - seqlen_q
        causal_mask = tf.cast(causal_mask, dtype=tf.float32)
        scores = mask_fill(scores, causal_mask, -10000.0)
        # end of causal stuff
        attention = tf.nn.softmax(scores, axis=-1)
        attention = tf.cast(attention, dtype=v.dtype)
        output = tf.einsum("bhts,bshd->bthd", attention, v)
        return output

class CrossAttention(nn.Module):
    def __init__(
        self, causal: bool = True, softmax_scale: Optional[float] = None,
        attention_dropout: float = 0.0) -> None:
        super().__init__()
        self.causal = causal
        self.softmax_scale = softmax_scale
        self.drop = nn.Dropout(attention_dropout)
    def forward(self, q: torch.FloatTensor, kv: torch.FloatTensor,causal: bool = None,
        key_padding_mask: Optional[torch.BoolTensor] = None, **kwargs) -> torch.FloatTensor:
        batch_size, seqlen_q = q.shape[0], q.shape[1]
        seqlen_k = kv.shape[1]
        if kv.shape[3] != q.shape[2]:
            kv = repeat(kv, "... hkv d -> ... (hkv g) d", g=q.shape[2] // kv.shape[3])
        k, v = kv.unbind(dim=2)
        q = q.to(torch.float32)
        k = k.to(torch.float32)
        causal = self.causal if causal is None else causal
        softmax_scale = self.softmax_scale or 1.0 / math.sqrt(q.shape[-1])
        # Autocast is manually disabled to avoid `torch.einsum` performing the operation
        # using float16, which might lead to overflow
        print(q.shape)
        print(kv.shape)
        scores = torch.einsum("bthd,bshd->bhts", q, k * softmax_scale)
        if key_padding_mask is not None:
            padding_mask = torch.full(
                (batch_size, seqlen_k),
                -10000.0,
                dtype=scores.dtype,
                device=scores.device,
            )
            padding_mask.masked_fill_(key_padding_mask, 0.0)
            scores = scores + rearrange(padding_mask, "b s -> b 1 1 s")
        if causal:
            rows = rearrange(torch.arange(seqlen_q, device=q.device, dtype=torch.long), "s -> s 1")
            cols = torch.arange(seqlen_k, device=k.device, dtype=torch.long)
            causal_mask = cols > rows + seqlen_k - seqlen_q
            scores = scores.masked_fill(causal_mask, -10000.0)
        attention = torch.softmax(scores, dim=-1).to(v.dtype)
        attention = self.drop(attention)
        output = torch.einsum("bhts,bshd->bthd", attention, v)
        return output

cross_atten = CrossAttention(causal=True, softmax_scale=0.1)
my_cross_atten = MyCrossAttention(softmax_scale=0.1)

batch_size = 1
seq_len = 17
seqlen_k = 11
two = 2 # must be two
q = torch.randn(batch_size, seq_len, 20, 7)
kv = torch.randn(batch_size, seqlen_k, two, 5, 7)
key_padding_mask = torch.zeros((batch_size, seqlen_k), dtype=torch.float32)
key_padding_mask[0,0] += 1
key_padding_mask[0,1] += 1
key_padding_mask = key_padding_mask.to(bool)
out = cross_atten(q, kv, causal=True, key_padding_mask=key_padding_mask)

# print(out)
print("-----")
q = tf.constant(q.numpy())
kv = tf.constant(kv.numpy())
key_padding_mask = tf.constant(key_padding_mask.to(torch.float).numpy())
out = my_cross_atten(q, kv, key_padding_mask)
# print(out)



torch.Size([1, 17, 20, 7])
torch.Size([1, 11, 2, 20, 7])
-----
q (1, 17, 20, 7)
kv (1, 11, 2, 20, 7)
k (1, 11, 20, 7)
padding_mask: (1, 11)
key_padding_mask: (1, 11)


In [13]:
def MY_update_kv_cache(kv, inference_params, layer_idx:int):
    num_heads, head_dim = kv.shape[-2:]
    if layer_idx not in inference_params.key_value_memory_dict:
        # during the UDO desgin process, could use uninitalized memory rather than zeros
        inference_params.key_value_memory_dict[layer_idx] = tf.zeros(
            [
                inference_params.max_batch_size,
                inference_params.max_seqlen,
                2,
                num_heads,
                head_dim
            ],
            dtype=kv.dtype
        )
    batch_start = inference_params.batch_size_offset
    batch_end = batch_start + kv.shape[0]
    sequence_start = inference_params.seqlen_offset
    sequence_end = sequence_start + kv.shape[1]
    # When the current sequence length is equal to or larger than the maximum sequence length,
    # we need to concatenate the current `kv` with the cached `kv` to expand its length
    if sequence_end >= inference_params.max_seqlen:
        # the line below might fail due to the tuple
        inference_params.key_value_memory_dict[layer_idx] = tf.concat((inference_params.key_value_memory_dict[layer_idx], kv), axis=1)
    inference_params.key_value_memory_dict[layer_idx][batch_start:batch_end, sequence_start:sequence_end, ...] = kv
    kv = inference_params.key_value_memory_dict[layer_idx][batch_start:batch_end, :sequence_end, ...]
    return kv

In [14]:
def _find_mha_dims(
    config,
    n_head: Optional[int] = None,
    n_head_kv: Optional[int] = None,
    head_dim: Optional[int] = None,
):
    if n_head is None and head_dim is None:
        head_dim = config.n_embd // config.n_head
        n_head = config.n_head
    elif n_head is None or head_dim is None:
        raise ValueError("`n_head` and `head_dim` must be both specified or `None`.")
    if n_head_kv is None:
        n_head_kv = getattr(config, "n_head_kv", None) or n_head
    return n_head, n_head_kv, head_dim

In [59]:
# this is not my code

pad_input, unpad_input = None, None
FlashRotaryEmbedding = None
FlashSelfAttention, FlashCrossAttention = None, None
FusedDense = None

from typing import Any, Dict, Optional, Tuple, Union

from transformers import PretrainedConfig, PreTrainedModel

class MHA(nn.Module):
    """Multi-head attention layer."""

    def __init__(
        self,
        config: PretrainedConfig,
        dtype: Optional[torch.dtype] = None,
        device: Optional[str] = None,
        rotary_dim: Optional[int] = None,
        rotary_base: float = 10000.0,
        rotary_scale_base: Optional[float] = None,
        n_head: Optional[int] = None,
        n_head_kv: Optional[int] = None,
        head_dim: Optional[int] = None,
        bias: bool = True,
        causal: bool = True,
        softmax_scale: Optional[float] = None,
        layer_idx: Optional[int] = None,
        return_residual: bool = False,
        checkpointing: bool = False,
    ) -> None:
        super().__init__()

        # Rotary embedding
        self.rotary_dim = rotary_dim if rotary_dim is not None else getattr(config, "rotary_dim", 0)
        if self.rotary_dim > 0:
            rotary_cls = FlashRotaryEmbedding if config.flash_rotary else RotaryEmbedding
            if rotary_cls is None:
                rotary_cls = RotaryEmbedding

            rotary_kwargs = {}
            if rotary_cls is RotaryEmbedding:
                rotary_kwargs["max_position_embeddings"] = config.n_positions
            print("rotary cls:", rotary_cls)
            self.rotary_emb = rotary_cls(
                self.rotary_dim,
                base=rotary_base,
                scale_base=rotary_scale_base,
                pos_idx_in_fp32=True,
                max_position_embeddings=2048,
                device=device,)

        # MLP
        self.n_head, self.n_head_kv, self.head_dim = _find_mha_dims(
            config, n_head=n_head, n_head_kv=n_head_kv, head_dim=head_dim
        )
        op_size = self.head_dim * (self.n_head + 2 * self.n_head_kv)
        hidden_size = config.n_embd

        linear_cls = FusedDense if config.fused_dense else nn.Linear
        if linear_cls is None:
            linear_cls = nn.Linear

        self.Wqkv = linear_cls(hidden_size, op_size, bias=bias, device=device, dtype=dtype)
        self.out_proj = linear_cls(hidden_size, hidden_size, bias=bias, device=device, dtype=dtype)

        # Attention
        attn_cls = FlashSelfAttention if config.flash_attn else SelfAttention
        if attn_cls is None:
            attn_cls = SelfAttention

        cross_attn_cls = FlashCrossAttention if config.flash_attn else CrossAttention
        if cross_attn_cls is None:
            cross_attn_cls = CrossAttention

        self.inner_attn = attn_cls(
            causal=causal,
            softmax_scale=softmax_scale,
            attention_dropout=config.attn_pdrop,
        )
        self.inner_cross_attn = cross_attn_cls(
            causal=causal,
            softmax_scale=softmax_scale,
            attention_dropout=config.attn_pdrop,
        )

        self.flash_attn = config.flash_attn and attn_cls is FlashSelfAttention
        self.layer_idx = layer_idx
        self.return_residual = return_residual
        self.checkpointing = checkpointing

    def _forward_self_attn(
        self, x: torch.FloatTensor, key_padding_mask: Optional[torch.BoolTensor]
    ) -> torch.FloatTensor:
        qkv = self.Wqkv(x)
        qkv = rearrange(qkv, "... (three h d) -> ... three h d", three=3, d=self.head_dim)
        if self.rotary_dim > 0:
            qkv = self.rotary_emb(qkv)
        if self.flash_attn:
            batch_size, seqlen = qkv.shape[0], qkv.shape[1]
            cu_seqlens, max_seqlen = None, None
            if key_padding_mask is not None:
                # If `key_padding_mask` is supplied, we need to unpad the input and retrieve
                # the `cu_seqlens` and `max_seqlen` to be used by `flash-attn`
                qkv, indices, cu_seqlens, max_seqlen = unpad_input(qkv, key_padding_mask)
            if self.checkpointing:
                attn_output = torch.utils.checkpoint.checkpoint(
                    self.inner_attn, qkv, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen
                )
            else:
                attn_output = self.inner_attn(qkv, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen).to(qkv.device)
            # If `key_padding_mask` is supplied, we need to pad the output back to the original shape
            return pad_input(attn_output, indices, batch_size, seqlen) if key_padding_mask is not None else attn_output
        if self.checkpointing:
            return torch.utils.checkpoint.checkpoint(self.inner_attn, qkv, key_padding_mask=key_padding_mask)
        return self.inner_attn(qkv, key_padding_mask=key_padding_mask)

    def _forward_cross_attn(
        self,
        x: torch.FloatTensor,
        past_key_values,
        key_padding_mask: Optional[torch.BoolTensor],
    ) -> torch.FloatTensor:
        batch_size = x.shape[0]
        qkv = self.Wqkv(x)
        q = qkv[..., : self.n_head * self.head_dim]
        # print("q1:", q)
        q = rearrange(q, "... (h d) -> ... h d", d=self.head_dim)
        # print("q2:", q)
        kv = qkv[..., self.n_head * self.head_dim :]
        # print("kv1:", kv)
        kv = rearrange(kv, "... (two hkv d) -> ... two hkv d", two=2, d=self.head_dim)
        # print("kv2:", kv)
        seqlen_offset = past_key_values.seqlen_offset if past_key_values is not None else 0
        causal = None if seqlen_offset == 0 else False
        print("q SHAPE:", q.shape)
        print("kv SHAPE:", kv.shape)
        if self.rotary_dim > 0:
            q, kv = self.rotary_emb(q, kv=kv, seqlen_offset=seqlen_offset)
        if past_key_values is not None:
            kv = _update_kv_cache(kv, past_key_values, self.layer_idx)
        if self.flash_attn:
            batch_size, seqlen_q = q.shape[0], q.shape[1]
            seqlen_k = kv.shape[1]
            cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k = (
                None,
                None,
                None,
                None,
            )
            if key_padding_mask is not None:
                kv, _, cu_seqlens_k, max_seqlen_k = unpad_input(kv, key_padding_mask)
                if seqlen_q == 1:
                    key_padding_mask = torch.ones(batch_size, 1, device=q.device)
                elif seqlen_q != seqlen_k:
                    key_padding_mask = key_padding_mask[:, -seqlen_q:]
                q, indices_q, cu_seqlens_q, max_seqlen_q = unpad_input(q, key_padding_mask)
            if self.checkpointing:
                attn_output = torch.utils.checkpoint.checkpoint(
                    self.inner_cross_attn,
                    q,
                    kv,
                    causal=causal,
                    cu_seqlens=cu_seqlens_q,
                    max_seqlen=max_seqlen_q,
                    cu_seqlens_k=cu_seqlens_k,
                    max_seqlen_k=max_seqlen_k,
                )
            else:
                attn_output = self.inner_cross_attn(
                    q,
                    kv,
                    causal=causal,
                    cu_seqlens=cu_seqlens_q,
                    max_seqlen=max_seqlen_q,
                    cu_seqlens_k=cu_seqlens_k,
                    max_seqlen_k=max_seqlen_k,
                )
            return (
                pad_input(attn_output, indices_q, batch_size, max_seqlen_q)
                if key_padding_mask is not None
                else attn_output
            )
        if self.checkpointing:
            return torch.utils.checkpoint.checkpoint(
                self.inner_cross_attn,
                q,
                kv,
                key_padding_mask=key_padding_mask,
                causal=causal,
            )
        # print("q:", q)
        # print("kv:", kv)
        return self.inner_cross_attn(q, kv, key_padding_mask=key_padding_mask, causal=causal)
    def forward(
        self,
        x: torch.FloatTensor,
        past_key_values=None,
        attention_mask: Optional[Union[torch.LongTensor, torch.BoolTensor]] = None,
        **kwargs,
    ) -> Tuple[torch.FloatTensor, torch.FloatTensor]:
        if attention_mask is not None:
            attention_mask = attention_mask.bool()
        else:
            attention_mask = None
        # MHA
        if self.n_head == self.n_head_kv:
            if past_key_values is None:
                # If `past_key_values` are not supplied, we run self-attention
                attn_output = self._forward_self_attn(x, attention_mask)
            else:
                # If `past_key_values` are supplied, it means that we might have cached values and
                # could take advantage of cross-attention
                attn_output = self._forward_cross_attn(x, past_key_values, attention_mask)
        # MQA / GQA
        else:
            # Regardless of `past_key_values` being supplied or not, it always use cross-attention
            # because `q` and `kv` lengths might be different
            attn_output = self._forward_cross_attn(x, past_key_values, attention_mask)
        # print("attn_out:", attn_output)
        output = rearrange(attn_output, "... h d -> ... (h d)")
        # print("output:", output)
        output = self.out_proj(output)
        # print("output:", output)
        return output if not self.return_residual else (output, x)



In [65]:
# looks good!

# for now
FlashRotaryEmbedding = None
FusedDense = None
FlashSelfAttention = None
FlashCrossAttention = None


class MyMHA(tf.Module):
    def __init__(self, rotary_dim, rotary_base, rotary_scale_base,
                 n_head, n_head_kv, head_dim, bias:bool, softmax_scale:float,
                 layer_idx:int, return_residual:bool,
                 flash_rot_emb:bool, n_positions, n_embd,
                 fused_dense:bool,
                 flash_attn:bool, weights,
                 name=None):
        super().__init__(name)
        # Rotary embedding
        self.rotary_dim = rotary_dim
        if self.rotary_dim > 0:
            rotary_cls = FlashRotaryEmbedding if flash_rot_emb else MyRotaryEmbedding
            rotary_kwargs = {}
            if rotary_cls is MyRotaryEmbedding:
                rotary_kwargs["max_position_embeddings"] = n_positions
            self.rotary_emb =  rotary_cls(
                self.rotary_dim,
                base=rotary_base,
                scale_base=rotary_scale_base,
                pos_idx_in_fp32=True, # try the other way aswell
                max_position_embeddings=2048
            )
        # MLP
        self.n_head = n_head
        self.n_head_kv = n_head_kv
        self.head_dim = head_dim
        op_size = self.head_dim * (self.n_head + 2 * self.n_head_kv)
        hidden_size = n_embd
        linear_cls = FusedDense if fused_dense else bert.Dense_v2
        self.Wqkv = linear_cls(hidden_size, op_size, weights=weights['Wqkv_weights'], bias=None)
        self.out_proj = linear_cls(hidden_size, hidden_size, weights=weights['out_proj_weights'], bias=None)
        # Attention
        attn_cls = FlashSelfAttention if flash_attn else MySelfAttention
        cross_attn_cls = FlashCrossAttention if flash_attn else MyCrossAttention
        self.inner_attn = attn_cls(softmax_scale=softmax_scale)
        self.inner_cross_attn = cross_attn_cls(softmax_scale=softmax_scale)
        self.flash_attn = flash_attn and attn_cls is FlashSelfAttention
        self.layer_idx = layer_idx
        self.return_residual = return_residual

    def _forward_self_attn(self, x, key_padding_mask):
        qkv = self.Wqkv(x)
        h = qkv.shape[-1] // (3 * self.head_dim)
        assert(h * 3 * self.head_dim == qkv.shape[-1])
        qkv = tf.reshape(qkv, qkv.shape[:-1] + [3, h, self.head_dim])
        if self.rotary_dim > 0:
            qkv = self.rotary_emb(qkv)
        return self.inner_attn(qkv, key_padding_mask=key_padding_mask)
    
    def _forward_cross_attn(self, x, past_key_values, key_padding_mask):
        batch_size = x.shape[0]
        print("x.shape:", x.shape)
        qkv = self.Wqkv(x)
        q = qkv[..., : self.n_head * self.head_dim]
        # print("q1:", q)
        print("q inital shape:", q.shape)
        h = q.shape[-1] // self.head_dim
        print("h:", h)
        assert(h * self.head_dim == q.shape[-1])
        q = tf.reshape(q, q.shape[:-1] + [h, self.head_dim])
        # print("q2:", q)
        print("q final shape:", q.shape)
        kv = qkv[..., self.n_head * self.head_dim :]
        # print("kv1:", kv)
        print("kv 1st shape:", kv.shape)
        hkv = kv.shape[-1] // (2 * self.head_dim)
        assert(hkv * 2 * self.head_dim == kv.shape[-1])
        kv = tf.reshape(kv, kv.shape[:-1] + [2, hkv, self.head_dim])
        # print("kv2:", kv)
        print("kv second shape:", kv.shape)
        seqlen_offset = past_key_values.seqlen_offset if past_key_values is not None else 0
        causal = None if seqlen_offset == 0 else False
        # print("q:", q)
        # print("kv:", kv)
        if self.rotary_dim > 0:
            q, kv = self.rotary_emb(q, kv=kv, seqlen_offset=seqlen_offset)
        if past_key_values is not None:
            kv = MY_update_kv_cache(kv, past_key_values, self.layer_idx)
        # print("q:", q)
        # print("kv:", kv)
        return self.inner_cross_attn(q, kv, key_padding_mask=key_padding_mask)
    def __call__(self, x, past_key_values, attention_mask):
        # assert(attention_mask is not None)
        # attention_mask = tf.cast(attention_mask, dtype=tf.bool)
        # MHA
        if self.n_head == self.n_head_kv:
            if past_key_values is None:
                # If `past_key_values` are not supplied, we run self-attention
                attn_output = self._forward_self_attn(x, attention_mask)
            else:
                # If `past_key_values` are supplied, it means that we might have cached values and
                # could take advantage of cross-attention
                attn_output = self._forward_cross_attn(x, past_key_values, attention_mask)
        # MQA / GQA
        else:
            # Regardless of `past_key_values` being supplied or not, it always use cross-attention
            # because `q` and `kv` lengths might be different
            attn_output = self._forward_cross_attn(x, past_key_values, attention_mask)
        # print("attn_out:", attn_output)
        output = tf.reshape(attn_output, attn_output.shape[:-2] + [attn_output.shape[-1] * attn_output.shape[-2]])
        output = self.out_proj(output)
        # print("output:", output)
        return output if not self.return_residual else (output, x)

rotary_dim = 5
rotary_base = 10000.0
rotary_scale_base = None # this seemsm neccesary
n_head = 10
n_head_kv = 5
head_dim = 6
bias = False
softmax_scale = 2.3
layer_idx = 2
return_residual = False
flash_rot_emb = False
n_positions = 30 # idk what this should be
n_embd = 60 # i think n_head * head_dim is required
fused_dense = False
flash_attn = False

op_size = head_dim * (n_head + 2 * n_head_kv)
print("op_size:", op_size)

# for their class
class PhiConfig():
    def __init__(self):
        self.flash_rotary = False
        self.n_positions = n_positions
        self.n_embd = n_embd
        self.fused_dense = False
        self.flash_attn= False
        self.attn_pdrop = 0


config = PhiConfig()
mha = MHA(config, torch.float32, 'cpu', rotary_dim, rotary_base, rotary_scale_base, 
          n_head, n_head_kv, head_dim, False, True, softmax_scale, layer_idx, False, False)

weights = {}
# weights['Wqkv_weights'] = tf.random.uniform((n_embd, op_size))
# weights['out_proj_weights'] = tf.random.uniform((n_embd, n_embd))
weights['Wqkv_weights'] = tf.constant(mha.Wqkv.weight.clone().detach().numpy())
weights['Wqkv_weights'] = tf.transpose(weights['Wqkv_weights'])
weights['out_proj_weights'] = tf.constant(mha.out_proj.weight.clone().detach().numpy())
weights['out_proj_weights'] = tf.transpose(weights['out_proj_weights'])

print(weights)

my_mha = MyMHA(rotary_dim, rotary_base, rotary_scale_base,
                 n_head, n_head_kv, head_dim, bias, softmax_scale,
                 layer_idx, return_residual,
                 flash_rot_emb, n_positions, n_embd,
                 fused_dense,
                 flash_attn, weights)

key_padding_mask = torch.zeros((batch_size, seqlen_k), dtype=torch.float32)
key_padding_mask[0,0] += 1
key_padding_mask[0,1] += 1
# key_padding_mask = key_padding_mask.to(bool)
# key_padding_mask = tf.constant(key_padding_mask.numpy())

# input = torch.randn([3,7,11, 13, n_embd])
input = torch.randn([batch_size, seqlen_k, n_embd])

out = mha(input, None, key_padding_mask)
print("out:", out)


input = tf.constant(input.numpy())
key_padding_mask = tf.constant(key_padding_mask.numpy())

out = my_mha(x=input, past_key_values=None, attention_mask=key_padding_mask)
print("out:", out)



op_size: 120
rotary cls: <class '__main__.RotaryEmbedding'>
{'Wqkv_weights': <tf.Tensor: shape=(60, 120), dtype=float32, numpy=
array([[ 0.07678058, -0.07007174,  0.05891553, ...,  0.00992144,
        -0.00672298, -0.02630917],
       [-0.07346928,  0.02912661,  0.10963711, ...,  0.04504179,
        -0.06488528,  0.04778528],
       [ 0.10964601, -0.01543122, -0.1091646 , ..., -0.11678492,
        -0.10441844, -0.04532752],
       ...,
       [ 0.09467129,  0.00772457,  0.0470764 , ...,  0.10836332,
        -0.08057441,  0.11006826],
       [-0.079307  , -0.06699201, -0.09228462, ..., -0.00885021,
        -0.11001061, -0.0755408 ],
       [-0.10742576,  0.12564814,  0.05507148, ..., -0.0084542 ,
         0.07647138, -0.06237472]], dtype=float32)>, 'out_proj_weights': <tf.Tensor: shape=(60, 60), dtype=float32, numpy=
array([[ 0.02931975, -0.05140317,  0.03600217, ..., -0.04946491,
         0.12587316, -0.0936538 ],
       [-0.03755412, -0.09317454, -0.12040319, ..., -0.01674604,
       

In [ ]:
class MyParallelBlock(tf.Module):
    def __init__(self, block_idx, name=None):
        super().__init__(name)
        self.ln = bert.LayerNorm(weights=None, biases=None, eps=None)
        self.block_idx = block_idx
        self.mixer = MyMHA()
        self.mlp = MyMLP()
    
    def __call__(self, hidden_states, past_key_values, attention_mask):
        residual = hidden_states
        hidden_states = self.ln(hidden_states)
        attn_outputs = self.mixer(
            hidden_states,
            past_key_values=past_key_values,
            attention_mask=attention_mask,
        )
        if isinstance(attn_outputs, tuple):
            attn_outputs = attn_outputs[0]
        feed_forward_hidden_states = self.mlp(hidden_states)
        hidden_states = attn_outputs + feed_forward_hidden_states + residual
        return hidden_states

In [ ]:
class MyCausalLMHead(tf.Module):
    def __init__(self, n_embd, layer_norm_eps, vocab_size, name=None):
        super().__init__(name)
        self.ln = nn.LayerNorm(n_embd, eps=layer_norm_eps)
        self.linear = bert.Dense_v2(n_embd, vocab_size)
    def __call__(self, hidden_states):
        hidden_states = self.ln(hidden_states)
        logits = tf.cast(self.linear(hidden_states), dtype=tf.float32)
        return logits

In [ ]:
# class MyPhiPreTrainedModel(tf.Module):
    